### ISSUE TITLE
Need to declare twice the same ignore

### ISSUE THREAD

**Issue by surli** [revapi/revapi#220] opened 2020-11-26 10:31 UTC
Hi,

I recently got an issue in a project where I needed to declare twice the same ignore configuration for revapi to avoid complaining about an API change. 
Here's the commit where the problem happened: https://github.com/xwiki-contrib/application-activitypub/commit/bfe60106a5c3417ba5f15f35808437d6c9b549d3#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R130

Note that I thought at a point that it was an order issue of the declaration of the ignores, so I tried to removed the first ones, but then I got it complaining about API changes. Also note that I got the problem when building the whole project, those API changes are located in `activitypub-core` submodule, but I think it complains about the missing ignores when building `activitypub-notifications` submodule, probably when checking transitive dependencies.

**Comment by metlos** [comment] 2020-11-30 14:13
Interesting. I can't tell what might be the cause of this from the top of my head. Will try debug this as time permits...

**Comment by manuelleduc** [comment] 2020-12-17 11:10
Hello,

I also working on the same project. I've restarted from an empty `revapi.ignore` for the development of the next version and encountered the same issue.

All the items declared below this comment https://github.com/xwiki-contrib/application-activitypub/blob/f01eb350fcf26d7e6d108b17e4e9c0b5eaa4277b/pom.xml#L130 are duplicates of items declared above this comment.
Some items needs to be declared more than twice to make revapi pass.

**Comment by metlos** [comment] 2021-01-08 22:51
I'm hoping this is just a duplicate of #221. Could you please confirm with @vmassol that that is indeed the case?

**Comment by vmassol** [comment] 2021-01-13 13:06
I'll update here once I get the new version working and #221 is solved.

**Closed** 2021-11-12 00:16 UTC
