### ISSUE TITLE
[ERROR] Failed to scan class XXXX. Analysis results may be skewed

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#101] opened 2017-10-30 10:37 UTC
Now revapi runs, and the revapi phase does not fail.
Still we have error messages and strange results. Any idea?

```
[ERROR] Failed to scan class org.eclipse.jdt.internal.core.JavaProject. Analysis results may be skewed.
java.lang.IllegalStateException: Could not determine the element of a type: org.eclipse.core.runtime.CoreException
	at org.revapi.java.compilation.ClasspathScanner$Scanner$1.defaultAction(ClasspathScanner.java:215)
	at org.revapi.java.compilation.ClasspathScanner$Scanner$1.defaultAction(ClasspathScanner.java:212)
	at javax.lang.model.util.SimpleTypeVisitor6.visitError(SimpleTypeVisitor6.java:182)
	at com.sun.tools.javac.code.Type$ErrorType.accept(Type.java:1855)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.lambda$scanMethod$24(ClasspathScanner.java:476)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.scanMethod(ClasspathScanner.java:475)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.scanClass(ClasspathScanner.java:353)
	at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:171)
	at org.revapi.java.compilation.Compiler.lambda$compile$72(Compiler.java:123)
	at org.revapi.java.compilation.ProbingAnnotationProcessor.process(ProbingAnnotationProcessor.java:53)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:67)
	at org.revapi.java.compilation.ProbingAnnotationProcessor$1.call(ProbingAnnotationProcessor.java:77)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Failed to scan class org.eclipse.jdt.internal.core.JarPackageFragmentRoot. Analysis results may be skewed.
java.lang.IllegalStateException: Could not determine the element of a type: org.eclipse.core.runtime.CoreException
	at org.revapi.java.compilation.ClasspathScanner$Scanner$1.defaultAction(ClasspathScanner.java:215)
	at org.revapi.java.compilation.ClasspathScanner$Scanner$1.defaultAction(ClasspathScanner.java:212)
	at javax.lang.model.util.SimpleTypeVisitor6.visitError(SimpleTypeVisitor6.java:182)
	at com.sun.tools.javac.code.Type$ErrorType.accept(Type.java:1855)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.lambda$scanMethod$24(ClasspathScanner.java:476)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.scanMethod(ClasspathScanner.java:475)
	at org.revapi.java.compilation.ClasspathScanner$Scanner.scanClass(ClasspathScanner.java:353)
	at org.revapi.java.compilation.ClasspathScanner.initTree(ClasspathScanner.java:171)
	at org.revapi.java.compilation.Compiler.lambda$compile$72(Compiler.java:123)
	at org.revapi.java.compilation.ProbingAnnotationProcessor.process(ProbingAnnotationProcessor.java:53)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:67)
	at org.revapi.java.compilation.ProbingAnnotationProcessor$1.call(ProbingAnnotationProcessor.java:77)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metlos** [comment] 2017-10-30 13:47
What version of `revapi-java` are you using?

**Comment by metlos** [comment] 2017-10-30 14:36
I'm seeing `revapi-java-0.14.2` in https://github.com/INRIA/spoon/pull/1665 but the line numbers in the above stack trace don't correspond to that...

**Comment by monperrus** [comment] 2017-10-30 15:30
What you see in https://github.com/INRIA/spoon/pull/1665 corresponds to the trace.

Is there a way to force Maven to tell the plugin versions it's loading and using?

(in the meantime, I'll try to flush the local cache)

**Comment by monperrus** [comment] 2017-10-30 15:55
by flushing the local `.m2`, there is still the same error.

**Comment by metlos** [comment] 2017-10-30 16:01
when you run Maven with `-X`, it will tell you the dependencies of plugins. Look for the start of the revapi-maven-plugin execution and you will find the dependency tree right at the start of it.

**Comment by metlos** [comment] 2017-10-30 16:02
In the meantime, I'll try checking out your branch and reproduce it locally...

**Comment by metlos** [comment] 2017-10-30 19:13
Ok, so the issue is two fold.

1) Revapi unnecessarily freaks out on a missing class in certain situations. A fix is simple and I have it ready, actually.
2) Spoon depends on `org.eclipse.jdt.core` which declares its dependencies only the OSGi way in manifest, but not in Maven pom. Revapi thus fails to compose the full transitive closure of dependencies and encounters missing classes.

Point 1) should be solvable by a new release of `revapi-java` to which I hope to get to later this evening or tomorrow...
Point 2) is more  complex - I have currently no plans to figure out the full dependency tree using OSGi runtime, but contributions are always welcome. If you or anyone reading this would like to take a look at that, I'm more than willing to discuss it and help out if possible.

**Comment by monperrus** [comment] 2017-10-30 19:34
> Revapi unnecessarily freaks out on a missing class in certain situations. A fix is simple and I have it ready, actually. I hope to get to later this evening or tomorrow...

Excellent, thanks.

> Spoon depends on org.eclipse.jdt.core which declares its dependencies only the OSGi way in manifest, but not in Maven pom

Yes, the core features of org.eclipse.jdt.core can be used without the whole Eclipse runtime. This is actually what Spoon does, it uses JDT-core without requiring the Eclipse runtime in the classpath.

**Comment by metlos** [comment] 2017-10-31 08:18
btw, @rfer, this seems to be the same problem you mentioned on IRC - I could not reply to you in time before you logged off again...

**Comment by metlos** [comment] 2017-10-31 14:08
This should be now fixed with `revapi-java-0.14.4`.

**Closed by metlos** 2017-10-31 14:08 UTC

**Comment by monperrus** [comment] 2017-10-31 14:37
I confirm that it is fixed, thanks a lot!

Now we have the remaining #102 , in Spoon, we have disabled Reavpi temporarily in order to avoid those 5 permanent spurious changes.

**Comment by rfer** [comment] 2017-10-31 14:40
Thanks @metlos. For testing purposes I've actually solved the problem locally. I'll take a look at the changes to see if it matches my assumption.
