### ISSUE TITLE
Failure to detect the type change of a generic in the parameters/return type

### ISSUE THREAD

**Issue by JoseVazevedo** [revapi/revapi#149] opened 2019-04-23 08:22 UTC
Recently, we came across a breaking change that slipped through us. After investigating what caused the issue, and why revapi did not detect the breaking change, we verified that the issue was due to changing the type of a List. We assume this goes for changing the type of any generic, as it does not result in any detection from revapi's part.

We changed a parameter of a method from `List<A>` to `List<B>`. The parameter size remained the same. The only change was the List type for one of the parameters. 

Now, we want to consider this is a breaking change as any client code using the changed method may not compile (in our case, it didn't).

Is this a known issue or bad configuration from our part?

Thank you for the help!

**Comment by metlos** [comment] 2019-04-23 20:48
A change in a type parameter should be detected and is by classified differently based on the location where this happened.

`java.class.superTypeTypeParametersChanged` is by default source and binary potentially breaking, `java.method.returnTypeTypeParametersChanged` is binary non-breaking and source breaking, `java.method.parameterTypeParameterChanged` is binary non-breaking and source potentially breaking.

You should be able to reclassify that (https://revapi.org/modules/revapi-basic-features/extensions/reclassify.html) if you need.

Now if this was not reported at all, that is of course a bug and I would really appreciate if you could provide some test repo / code where this is reproducible.

**Comment by JoseVazevedo** [comment] 2019-04-24 15:01
I have developed a minimum working example to reproduce the bug and it is avaiable here: https://github.com/JoseVazevedo/revapi_paramtype_poc

We are not reclassifying anything, so this should be detected by default, right?

If there's anything else you need, please let me know!

**Comment by metlos** [comment] 2019-04-25 20:45
So the change in your example is in the type parameter of a method parameter, which is by default classified as not breaking binary compatibility and potentially breaking source compatibility.

It is not classified as breaking for neither because whether or not this actually breaks the compatibility depends on the usage of the parameter. For example if the method `mergeList(List<String>)` was changed to `mergeList(List<? extends String>)` (however silly that would be), the calling code would still work. There are cases where the change of the type parameter is always invalid, like change from `String` to `Integer` as in your case, but Revapi does not do as detailed analysis as would be required to distinguish that.

In your example repo, you configured the reporter to only output the breaking changes. So to make it work, you either need to reconfigure the reporter to also output `POTENTIALLY_BREAKING` changes (setting the `minSeverity` property to that value, or actually not set the `minSeverity` at all, because that is the default value of that property) or you need to add reclassify rules to change the classification according to your liking in the `analysisConfiguration` like so:

```xml
<revapi.reclassify>
  <item>
    <code>java.method.parameterTypeParameterChanged</code>
    <classify>
      <SOURCE>BREAKING</SOURCE>
    </classify>
  </item>
</revapi.reclassify>
```

I personally recommend to also always consider the potentially breaking changes and add ignore rules after human consideration of the individual findings (the default `minSeverity` is `POTENTIALLY_BREAKING` for this reason).

Alternatively, I would love to improve the generics analysis but it is currently quite low on the priority list. PRs are always welcome though ;)

**Comment by metlos** [comment] 2019-04-25 20:53
I'm closing this issue because Revapi seems to work as designed in this case.

**Closed by metlos** 2019-04-25 20:53 UTC
