### ISSUE TITLE
External JSON configuration does not work

### ISSUE THREAD

**Issue by matthiasstock** [revapi/revapi#183] opened 2020-05-19 17:52 UTC
# Description

I am not able to externalize the configuration to a JSON file that ignores reported problems. Although I'm afraid of a user error, it could be a bug or is at least be suitable for the FAQ.

# Minimal example

I have set up a simple example at https://github.com/matthiasstock/revapi-issue. This example contains:

- Generating a Spring Boot 2.2.7 project using [start.spring.io](https://start.spring.io) with the default settings ([initial commit](https://github.com/matthiasstock/revapi-issue/commit/331d72475d05c330dd1a0e9b3d38e2db08d8bf6a))
- [Downgrade](https://github.com/matthiasstock/revapi-issue/commit/5a4ce0a4e41803ab48c0a6f7f14ecb3166fc911a) the Spring Boot version to 2.2.6 and `./mvnw install` it as the "old" 0.0.1 version
- [Upgrade](https://github.com/matthiasstock/revapi-issue/commit/e75fd64a856b856c53019a590576d3aeefb5470f) the Spring Boot version to 2.2.7 and `./mvnw install` it as the "new" 0.0.2-SNAPSHOT version
- Provide a `revapi-maven-plugin` [configuration for reproduction](https://github.com/matthiasstock/revapi-issue/commit/02da991164c16ad6c5576edb7743fd1fc8eb9f66)

## Manual tests

`./mvnw clean revapi:check` for various plugin configurations that should ignore the following problem:

```
[ERROR] java.class.nonPublicPartOfAPI: class org.springframework.boot.loader.jar.JarEntry: Class 'org.springframework.boot.loader.jar.JarEntry' is indirectly included in the API (by the means of method return type for example) but the class is not accessible (neither public nor protected).
```

## Expected Behavior

The configuration under `analysisConfiguration` and within `revapi-docs-new.json` works.

## Actual Behavior

Only the configuration under `analysisConfiguration` works.

## Remarks

The other two JSON files merely document other approaches and are not essential to this issue.

**Comment by metlos** [comment] 2020-05-27 22:00
The reproducer repo is super useful, thank you. I have not had a chance to take a look at it yet, though.

**Comment by metlos** [comment] 2020-05-28 15:05
First of all, please upgrade to `revapi-java:0.21.0` that I released yesterday, if at all possible. `0.20.2` had an ugly error in the textual representation of the java elements (the part in the parentheses mentioning the archive etc).

Now to you issue - you have a simple error in your configuration.

Try to run `./mvnw revapi:validate-configuration` and you will see that revapi has this to say:
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.11.4:validate-configuration (default-cli) on project demo: Failed to validate configuration. Errors: invalid type: object (expected array) @ /[0]/configuration  -> [Help 1]
```

Which is not that super helpful, but given the fact you have a single file in the configuration active, you can see that the `configuration` of the `revapi.ignore` should be an array, while you have an object.

So rewriting `revapi-docs-new.json` to read:
```json
[
  {
    "extension": "revapi.ignore",
    "configuration": [
      { 
        "code": "java.class.nonPublicPartOfAPI",
        "new": "class org.springframework.boot.loader.jar.JarEntry",
        "justification": "as in documentation: JSON Configuration Format"
      }
    ]
  }
]
```

fixes your problem. `revapi:validate-configuration` goal succeeds with this change and `revapi:check` succeeds as well, because it is able to use the configuration.

You can read the documentation for the ignore settings here: https://revapi.org/modules/revapi-basic-features/extensions/ignore.html.

Note that Revapi silently ignores configuration formatting errors mainly due to technical reasons - I implemented this in ancient times when there was no good json schema validator for java and so I am using a javascript based one that I invoke using java's script engine. You can imagine that this is not performing too well and substantially increases the runtime of the API check. I therefore opted to not run it on every analysis.

See https://github.com/revapi/revapi/issues/142 which I wrote down to track this problem.

I'm closing this issue but if you have any more questions or comments feel free to either submit a new issue or ask on the mailing list https://groups.google.com/forum/#!forum/revapi.

**Closed by metlos** 2020-05-28 15:05 UTC
